### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by Chemik-srem** [shirubei/simcalWithAdmobs#2]
Hi, I'm getting the below errors when it builds. I used your recipe. Maybe you know how to solve this problem?

### Showing All Errors Only
Undefined symbol: _GULIsLoggableLevel

Undefined symbol: _GULLogBasic

Undefined symbol: _GULLogError

Undefined symbol: _GULLogInfo

Undefined symbol: _GULLogWarning

Undefined symbol: _GULSetLoggerLevel

Undefined symbol: _OBJC_CLASS_$_GULAppDelegateSwizzler

Undefined symbol: _OBJC_CLASS_$_GULAppEnvironmentUtil

Undefined symbol: _OBJC_CLASS_$_GULMutableDictionary

Undefined symbol: _OBJC_CLASS_$_GULNetwork

Undefined symbol: _OBJC_CLASS_$_GULSwizzler

Undefined symbol: _kGULNetworkHTTPStatusCodeCannotAcceptTraffic

Undefined symbol: _kGULNetworkHTTPStatusCodeNotFound

Undefined symbol: _kGULNetworkHTTPStatusCodeNotModified

Undefined symbol: _kGULNetworkHTTPStatusCodeUnavailable

Undefined symbol: _kGULNetworkHTTPStatusNoContent

Undefined symbol: _kGULNetworkHTTPStatusOK

Undefined symbol: _pb_decode

Undefined symbol: _pb_decode_varint

Undefined symbol: _pb_encode

Undefined symbol: _pb_encode_string

Undefined symbol: _pb_encode_submessage

Undefined symbol: _pb_encode_tag_for_field

Undefined symbol: _pb_encode_varint

Undefined symbol: _pb_istream_from_buffer

Undefined symbol: _pb_ostream_from_buffer

Undefined symbol: _pb_read

**Comment by Chemik-srem** [comment]
So far, what I've been able to check is that I have a bug in architecture. If I change to 84x64, then the compilation builds, but I can't open it on a virtual device.

**Comment by Chemik-srem** [comment]
So far, what I've been able to check is that I have a bug in architecture. If I change to 84x64, then the compilation builds, but I can't open it on a virtual device.

**Comment by shirubei** [comment]
Have no idea, My macpro has an intel x86 CPU. Maybe it's something about architecture as you had pointout.

**Comment by Chemik-srem** [comment]
I have M1 Mac. Solved: Xcode open in rosetta.

Thanks [shirubei] your solution works great.

**Comment by loldjy123** [comment]
> So far, what I've been able to check is that I have a bug in architecture. If I change to 84x64, then the compilation builds, but I can't open it on a virtual device.

I'm so sorry for that thumb question I'm new in building ios app, I wanted to know how can i change the architecture please ?

**Comment by Chemik-srem** [comment]
> wiedzieć

Xcode Build setting/ architecture
